CREATE TABLE profesores(
	PRO_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PRO_NOMBRE VARCHAR(45) NOT NULL,
  PRO_APELLIDO VARCHAR(45) NOT NULL,
	PRO_DIRECCION VARCHAR(45),
  PRO_NUMERO INT(4),
  PRO_CELULAR INT(45),
  PRO_FIJO INT(45),
	PRO_CUIL INT(11),
  PRO_NACIMIENTO DATE
);
