CREATE TABLE ins27.profesores(
  PRO_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PRO_NOMBRE VARCHAR(45) NOT NULL,
  PRO_APELLIDO VARCHAR(45) NOT NULL,
  PRO_DIRECCION VARCHAR(45),
  PRO_NUMERO VARCHAR(4),
  PRO_CELULAR VARCHAR(45),
  PRO_FIJO VARCHAR(45),
  PRO_CUIL VARCHAR(11),
  PRO_NACIMIENTO DATE
);
